dependencies {
    implementation project(':api')

    implementation 'io.github.lsd-consulting:lsd-logging-library:1.0.18'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-jackson2'
    implementation 'org.springframework.boot:spring-boot-http-converter'
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'

    implementation 'io.micrometer:micrometer-tracing-bridge-brave'

    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}
